### ISSUE TITLE
about metadata

### ISSUE THREAD

**Issue by jlduan** [cartal/HCA_Heart#2]
Hi,

Thanks for the useful data.

I am a little confused about the metadata. I found it is a little difficult matching the raw bam files downloaded (Sample Accession) to the cell/sample names stored in the h5ad file provided (https://www.heartcellatlas.org/#DataSources).

For instance, the sample names (486,134 cells) stored in https://cellgeni.cog.sanger.ac.uk/heartcellatlas/data/global_raw.h5ad are

```
array(['H0015_LA_new', 'H0015_LV', 'H0015_RA', 'H0015_RV', 'H0015_apex',
       'H0015_septum', 'H0020_LA_new', 'H0020_LV', 'H0020_RA', 'H0020_RV',
       'H0020_apex', 'H0020_septum', 'H0025_LA', 'H0025_LV', 'H0025_RA',
       'H0025_RV', 'H0025_apex', 'H0025_septum', 'H0026_LA',
       'H0026_LV_V3', 'H0026_RA', 'H0026_RV', 'H0026_apex',
       'H0026_septum2', 'H0035_LA', 'H0035_LV', 'H0035_RA', 'H0035_RV',
       'H0035_apex', 'H0035_septum', 'H0037_Apex', 'H0037_LA_corr',
       'H0037_LV', 'H0037_RA_corr', 'H0037_RV', 'H0037_septum',
       'HCAHeart7606896', 'HCAHeart7656534', 'HCAHeart7656535',
       'HCAHeart7656536', 'HCAHeart7656537', 'HCAHeart7656538',
       'HCAHeart7656539', 'HCAHeart7664652', 'HCAHeart7664653',
       'HCAHeart7664654', 'HCAHeart7698015', 'HCAHeart7698016',
       'HCAHeart7698017', 'HCAHeart7702873', 'HCAHeart7702874',
       'HCAHeart7702875', 'HCAHeart7702876', 'HCAHeart7702877',
       'HCAHeart7702878', 'HCAHeart7702879', 'HCAHeart7702880',
       'HCAHeart7702881', 'HCAHeart7702882', 'HCAHeart7728604',
       'HCAHeart7728605', 'HCAHeart7728606', 'HCAHeart7728607',
       'HCAHeart7728608', 'HCAHeart7728609', 'HCAHeart7745966',
       'HCAHeart7745967', 'HCAHeart7745968', 'HCAHeart7745969',
       'HCAHeart7745970', 'HCAHeart7751845', 'HCAHeart7757636',
       'HCAHeart7757637', 'HCAHeart7757638', 'HCAHeart7757639',
       'HCAHeart7829976', 'HCAHeart7829977', 'HCAHeart7829978',
       'HCAHeart7829979', 'HCAHeart7833852', 'HCAHeart7833853',
       'HCAHeart7833854', 'HCAHeart7833855', 'HCAHeart7835148',
       'HCAHeart7835149', 'HCAHeart7836681', 'HCAHeart7836682',
       'HCAHeart7836683', 'HCAHeart7836684', 'HCAHeart7843999',
       'HCAHeart7844000', 'HCAHeart7844001', 'HCAHeart7844002',
       'HCAHeart7844003', 'HCAHeart7844004', 'HCAHeart7850539',
       'HCAHeart7850540', 'HCAHeart7850541', 'HCAHeart7850542',
       'HCAHeart7850543', 'HCAHeart7850544', 'HCAHeart7850545',
       'HCAHeart7850546', 'HCAHeart7850547', 'HCAHeart7850548',
       'HCAHeart7850549', 'HCAHeart7850551', 'HCAHeart7880860',
       'HCAHeart7880861', 'HCAHeart7880862', 'HCAHeart7880863',
       'HCAHeart7888922', 'HCAHeart7888923', 'HCAHeart7888924',
       'HCAHeart7888925', 'HCAHeart7888926', 'HCAHeart7888927',
       'HCAHeart7888928', 'HCAHeart7888929', 'HCAHeart7905327',
       'HCAHeart7905328', 'HCAHeart7905329', 'HCAHeart7905330',
       'HCAHeart7905331', 'HCAHeart7905332', 'HCAHeart7964513',
       'HCAHeart7985086', 'HCAHeart7985087', 'HCAHeart7985088',
       'HCAHeart7985089', 'HCAHeart8102858', 'HCAHeart8102859',
       'HCAHeart8102860', 'HCAHeart8102861', 'HCAHeart8102862',
       'HCAHeart8102863', 'HCAHeart8102864', 'HCAHeart8102865',
       'HCAHeart8102866', 'HCAHeart8102867', 'HCAHeart8102868',
       'HCAHeart8287123', 'HCAHeart8287124', 'HCAHeart8287125',
       'HCAHeart8287126', 'HCAHeart8287127', 'HCAHeart8287128'],
      dtype=object)
```

Is there a table providing the info matching the raw bam files listed here: https://www.ebi.ac.uk/ena/browser/view/PRJEB39602

For example, which bam file is H0015_LA_new, which is HCAHeart7606896?

Thank you!

**Comment by cartal** [comment]
I'm terribly sorry for this slow reply with this. 

You can now find the reads in the DCP [here](https://data.humancellatlas.org/explore/projects/ad98d3cd-26fb-4ee3-99c9-8a2ab085e737?catalog=dcp2) and all the information you need is in Supplementary Table 22 in our paper. 

Let me know if you need anything else.

**Comment by jlduan** [comment]
Hi,

Thanks for the link and this great dataset!

**Comment by jlduan** [comment]
Hi,

Sorry to bother you again on this issue.

In the Supplementary Table 22, there are two LA samples having similar names: 'H0037_LA_corr' and 'H0037_LA'. 

1) In the h5ad file, there is only 'H0037_LA_corr' sample. 
2) For the fastq files on HCA's DCP, there are only fastq files with prefix 'H0037_LA', no H0037_LA_corr'

Are they the same? (And are H0037_RA_corr and H0037_RA the same too?) 

Thanks.

**Comment by cartal** [comment]
Hi again, 

There are the same. Sorry about this. We will find a way to correct the reads in the next DCP release.

**Comment by jlduan** [comment]
Hi @cartal,

I am wondering if the corrected fastq files have been updated? Or where can I find the links or email to. Thank you very much!

Best,
Jialei

**Comment by cartal** [comment]
Dear @jiduan,

The reads are available from the DCP portal. You can get them [here](https://data.humancellatlas.org/explore/export/get-curl-command?filter=%5B%7B"facetName":"projectId","terms":%5B"ad98d3cd-26fb-4ee3-99c9-8a2ab085e737"%5D%7D,%7B"facetName":"genusSpecies","terms":%5B"Homo%20sapiens"%5D%7D,%7B"facetName":"fileFormat","terms":%5B"fastq.gz"%5D%7D%5D).

Let me know if you have any issues.
