### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by chenx9** [cartal/HCA_Heart#4]
Hi,
Thanks for the useful data.
I am a little confused about the metadata. I'm not sure what the 'NRP' column in the metadata means, this column contains 'yes' and 'no', I'm not sure what they mean.
<img width="410" alt="1650542518(1)" src="https://user-images.githubusercontent.com/81292404/164453936-896e90d1-7a9e-4b60-8ccc-35bf08894b30.png">

**Comment by cartal** [comment]
Dear @chenx9 

Thank you very much for your interest in our study.

NRP stands for Normothermic Regional Perfusion and in the metadata table it indicates of the heart received that treatment (Yes) or if it didn't (No).

Normothermic regional perfusion (NRP) is used to restore the flow of oxygenated blood following cardiac arrest and reverse warm ischemic injury in donation after circulatory death (DCD) organ transplantation. The use of NRP in this setting has typically been limited to the abdominal cavity, though its use has recently been expanded to chest to help recover DCD hearts, as well. 

I hope this helps!

**Comment by chenx9** [comment]
Thank you!
